### ISSUE TITLE
Hey fellow Chromebook kernel developer!

### ISSUE THREAD

**Issue by Apacelus** [gompa/Gkernel#1]
I couldn't find a way to contact you (except Twitter), so I'll just make an issue here.

I am Apacelus, the main dev of the [Eupnea Project](https://eupnea-linux.github.io/). We do a lot of Chromebook related things, including a modified linux kernel. Perhaps you would like to join our team to work with us on our kernel?

**Comment by gompa** [comment]
Thanks for reaching out Apacelus! This is just a hobby project, but I am open to discussing options for collaboration. What is the best way for me to get in contact with you? Looking forward to hearing from you.

**Comment by Apacelus** [comment]
Best way would be to join our discord server, https://discord.gg/jxXb2PwzYz
